Repository dlr-gtlab/intelligraph-module, pull requests merged in 2024-10, with the labels that each got.

#189 Resolve "Refactor the graph execution model to properly support nested graphs"
  CHANGELOG.md
  src/CMakeLists.txt
  src/graphdatamodel.h
  src/intelli/calculators/graphexeccalculator.cpp
  src/intelli/data/object.cpp
  src/intelli/data/object.h
  src/intelli/exec/detachedexecutor.cpp
  src/intelli/exec/detachedexecutor.h
  src/intelli/exec/dummynodedatamodel.cpp
  src/intelli/exec/dummynodedatamodel.h
  src/intelli/future.cpp
  src/intelli/future.h
  src/intelli/globals.h
  src/intelli/graph.cpp
  src/intelli/graph.h
  src/intelli/graphbuilder.cpp
  src/intelli/graphconnectionmodel.h
  src/intelli/graphdatamodel.h
  src/intelli/graphexecmodel.cpp
  src/intelli/graphexecmodel.h
  src/intelli/gui/grapheditor.cpp
  src/intelli/gui/grapheditor.h
  src/intelli/gui/graphics/connectionobject.cpp
  src/intelli/gui/graphics/connectionobject.h
  src/intelli/gui/graphics/nodeevalstateobject.cpp
  src/intelli/gui/graphics/nodeevalstateobject.h
  src/intelli/gui/graphics/nodeobject.cpp
  src/intelli/gui/graphics/nodeobject.h
  src/intelli/gui/graphscene.cpp
  src/intelli/gui/graphscene.h
  src/intelli/gui/graphview.cpp
  src/intelli/gui/graphview.h
  src/intelli/gui/nodegeometry.cpp
  src/intelli/gui/nodegeometry.h
  src/intelli/gui/nodeui.cpp
  src/intelli/gui/style.h
  src/intelli/node.cpp
  src/intelli/node.h
  src/intelli/node/abstractgroupprovider.h
  src/intelli/node/sleepy.cpp
  src/intelli/node/sleepy.h
  src/intelli/nodedatainterface.h
  src/intelli/nodeexecutor.cpp
  src/intelli/nodeexecutor.h
  src/intelli/private/graphexecmodel_impl.h
  src/intelli/private/node_impl.h
  src/intelli/private/utils.h
  tests/unittests/CMakeLists.txt
  tests/unittests/main.cpp
  tests/unittests/node/test_node.cpp
  tests/unittests/node/test_node.h
  tests/unittests/test_graph.cpp
  tests/unittests/test_graphexecmodel.cpp
  tests/unittests/test_helper.h
Labels: gtlab::intelligraphs, type::feature

#194 Resolve "Creating a new project using the intelli-graph module fails with GTlab 2.1.X"
  CHANGELOG.md
  src/intelli/package.cpp
Labels: type::bug

#197 Resolve "Update license text of some source files to BSD-3"
  src/intelli/exec/dummynodedatamodel.cpp
  src/intelli/exec/dummynodedatamodel.h
  src/intelli/future.cpp
  src/intelli/future.h
  src/intelli/node/fileinput.cpp
  src/intelli/node/fileinput.h
  src/intelli/node/filereader.cpp
  src/intelli/node/filereader.h
  src/intelli/node/filewriter.cpp
  src/intelli/node/filewriter.h
Labels: type::documentation

#196 Resolve: "Open Subgraphs in the same viewer but in a nested level"
  src/CMakeLists.txt
  src/intelli/data/object.cpp
  src/intelli/data/object.h
  src/intelli/future.cpp
  src/intelli/graphexecmodel.cpp
  src/intelli/graphexecmodel.h
  src/intelli/gui/grapheditor.cpp
  src/intelli/gui/grapheditor.h
  src/intelli/gui/graphics/nodeobject.cpp
  src/intelli/gui/graphics/nodeobject.h
  src/intelli/gui/graphscene.cpp
  src/intelli/gui/graphscene.h
  src/intelli/gui/graphscenemanager.cpp
  src/intelli/gui/graphscenemanager.h
  src/intelli/gui/graphsceneselector.cpp
  src/intelli/gui/graphsceneselector.h
  src/intelli/gui/graphstatemanager.cpp
  src/intelli/gui/graphstatemanager.h
  src/intelli/gui/graphview.cpp
  src/intelli/gui/graphview.h
  src/intelli/gui/graphviewoverlay.cpp
  src/intelli/gui/graphviewoverlay.h
  src/intelli/gui/style.h
  src/intelli/memory.h
  src/intelli/module.cpp
  src/intelli/node.h
  src/intelli/private/graphexecmodel_impl.h
  src/intelli/private/utils.h
  tests/unittests/test_graphexecmodel.cpp
  tests/unittests/test_helper.h
Labels: type::feature
